### ISSUE TITLE
it is not running in my windows 11 64 bit

### ISSUE THREAD

**Issue by ArianKhadem** [xibalbas/paper_trading_view#13]
Traceback (most recent call last):
  File "app.py", line 38, in <module>
  File "selenium\webdriver\chrome\webdriver.py", line 76, in init
  File "selenium\webdriver\remote\webdriver.py", line 157, in init
  File "selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 97
Current browser version is 103.0.5060.114 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 56, in <module>
RuntimeError: input(): lost sys.stdin

**Comment by enjoypython** [comment]
I have faced same error and found out this error occurs for those who have multiple chrome profiles which it leads to the profile selecting screen before the browser lands on the tradingview website

**Comment by f0cii** [comment]
This error message indicates that the version of ChromeDriver being used only supports Chrome version 97, while the current version of Chrome being used is 103.0.5060.114.

One solution to this issue would be to download the version of ChromeDriver that corresponds to the current version of Chrome being used. Another solution would be to downgrade the version of Chrome to version 97.

**Comment by alm0ra** [comment]
Dears @f0cii @enjoypython @ArianKhadem 

I don't have time to keep maintaining this project without your contribution 

Please feel free to open PR
