### ISSUE TITLE
user data directory is already in use

### ISSUE THREAD

**Issue by alm0ra** [xibalbas/paper_trading_view#9]
```
Traceback (most recent call last):
  File "[app.py]()", line 38, in <module>
  File "selenium\webdriver\chrome\[webdriver.py]()", line 76, in _init_
  File "selenium\webdriver\remote\[webdriver.py]()", line 157, in _init_
  File "selenium\webdriver\remote\[webdriver.py]()", line 252, in start_session
  File "selenium\webdriver\remote\[webdriver.py]()", line 321, in execute
  File "selenium\webdriver\remote\[errorhandler.py]()", line 242, in check_response
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[app.py]()", line 56, in <module>
RuntimeError: input(): lost sys.stdin
```

**Comment by hosseinadib-hub** [comment]
Hi 
appreciate for nice project

I got this error message too

**Comment by alm0ra** [comment]
Dear @amiradib . Thanks for your attention , i will handle this exception soon . 
But for now you should **Close** any chrome windows or **if you are using windows use tasks manage and end the task of chrome** . Then open the ptv

**Comment by Bishwas-py** [comment]
[This](https://webmatrices.com/d/504-invalid-argument-user-data-directory-is-already-in-use-selenium) helped my `user data directory is already in use` issue in selenium. I hope this helps you too.

**Comment by alm0ra** [comment]
@Bishwas-py dear bishwas , thanks for your attention . If you are a developer feel free to cobtribute on this project
